name: Build source files

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check if FastForward's rules have changed
        id: upstream_check
        uses: poll-github-repo/action@v1
        with:
          repo-to-sync: FastForwardTeam/FastForward
          path-to-sync: src/js/rules.json
          cache-path: .sync/rules.json.last-sync
          token: ${{ secrets.GITHUB_TOKEN }}
          yes-create-issues: false

      - name: Re-fetch rules from upstream, build
        if: steps.upstream_check.outputs.newCommitsInSyncRepo == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          wget https://raw.githubusercontent.com/FastForwardTeam/FastForward/master/src/js/rules.json -O fastforward/rules.json
          python build.py

      - name: New release if necessary
        run: gh release create $(date +%s) output/* --latest
        env:
          GH_TOKEN: ${{ github.token }}
